### ISSUE TITLE
Integrate newest version

### ISSUE THREAD

**Issue by Jamos1988** [openplotter/openplotter-pypilot#3]
Sorry, don't know how to do a pull request.
When updating OpenCPN the newest Pypilot plug-in is not compatible with the current version of openplotter-pypilot.
Can always install through GIT, but the I won't have the nice official openplotter pypilot app.

Can the newest version be integrated from Sean?

**Comment by sailoog** [comment]
openplotter-pypilot app gets pypilot code from a fork of @seandepagnier repo. Pypilot official repo is often updated with not tested changes so we need to relay only on no broken systems. To update this fork we need to test in deep the official repo and rebuild the logic of the pypilot integration in openplotter because signal k connections have changed. But besides this some important issues have to be fixed to start with this test round: https://github.com/pypilot/pypilot/issues/59
